### ISSUE TITLE
@RegisterRestClient but RestClientBuilder used

### ISSUE THREAD

**Issue by rdebusscher** [cicekhayri/ebook-Building-an-API-Backend-with-MicroProfile#14]
The `BookStoreService` has the `@RegisterRestClient` for creating a CDI bean capable of calling the remote endpoint.

This CDI bean is never used in the `BookStoreEndpoint` because there the Java API is used.

```
BookStoreService bookStoreService
                = RestClientBuilder.newBuilder()
                        .baseUrl(url)
                        .build(BookStoreService.class);

```
The Service needs to be `injected`.

**Comment by cicekhayri** [comment]
thanks @rdebusscher for the issue, I have updated the code and I would be grateful if you would like to check if I have done it right

**Comment by rdebusscher** [comment]
Looks better now. Thx
