### ISSUE TITLE
Add Continuous Integration using Travis + Github Pages

### ISSUE THREAD

**Issue by cesarhernandezgt** [cicekhayri/ebook-Building-an-API-Backend-with-MicroProfile#28]
Hi, 
It would be nice to have a CI for this repository so every commit will trigger Travis CI server to build latest master branch and publish online both PDF and HTML version using GithubPages.

I have a demo on how to do this on: https://github.com/cesarhernandezgt/book-demo-asciidoctor with the final output here: https://cesarhernandezgt.github.io/book-demo-asciidoctor/

What do you think?

**Comment by cicekhayri** [comment]
Hi @cesarhernandezgt 
That looks really nice

**Comment by cicekhayri** [comment]
Hi @cesarhernandezgt 

The travis-ci is integrated , thanks
