### ISSUE TITLE
TOC for html version missing headers levels and numbers

### ISSUE THREAD

**Issue by cesarhernandezgt** [cicekhayri/ebook-Building-an-API-Backend-with-MicroProfile#30]
Hi, I wonder if the removal of section numbers for the html TOC is on purpose [2]?
I tried to create a PR by updating the pom.xml section [1] for HTML wit the following but it didn't work so before keep investing time I choose to raise the question in this ticket.

[1]
```
 <id>output-html</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                        <configuration>
                            <backend>html5</backend>
                            <attributes>
                                <revnumber>${project.version}</revnumber>
                                <revremark>${revremark}</revremark>
                                <revdate>${revisiondate}</revdate>
                                <toc>left</toc>
                                <toclevels>4</toclevels>
                                <sectanchors>true</sectanchors>
                            </attributes>
                        </configuration>

```

[2]
![image](https://user-images.githubusercontent.com/1454523/62090899-cdf16d00-b22b-11e9-99ae-2bd5e4660d03.png)

**Comment by cicekhayri** [comment]
Hi @cesarhernandezgt 

I didn't remove the section numbers on purpose, I didn't see that the section numbers was missing :)

**Comment by cicekhayri** [comment]
Hi @cesarhernandezgt 

I have created PR which I think fixes this issue
